# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UIDtWmj0YxKRHTdH1TJOc-tLDlyyM9l
"""

import streamlit as st
import pickle
import pandas as pd

# ---------------------------
# Load Data
# ---------------------------

movies = pickle.load(open("movies.pkl", "rb"))
similarity = pickle.load(open("similarity.pkl", "rb"))

indices = pd.Series(
    movies.index,
    index=movies["title"]
).drop_duplicates()


# ---------------------------
# Recommendation Function
# ---------------------------

def recommend(movie):

    # Ignore upper/lower case
    movie = movie.strip()

    matched_movies = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    if matched_movies.empty:
        return "Movie not found!"

    idx = matched_movies.index[0]

    distances = list(enumerate(similarity[idx]))

    distances = sorted(
        distances,
        key=lambda x: x[1],
        reverse=True
    )

    recommendations = []

    for i in distances[1:6]:

        row = movies.iloc[i[0]]

        recommendations.append({
            "title": row["title"],
            "actors": row["actors"],
            "director": row["directors"],
            "genre": row["genre"],
            "year": row["releaseYear"],
            "hitFlop": row["hitFlop"]
        })

    return recommendations


# ---------------------------
# Streamlit UI
# ---------------------------

st.set_page_config(
    page_title="Bollywood Movie Recommendation System",
    page_icon="🎬",
    layout="wide"
)

st.title("🎬 Bollywood Movie Recommendation System")

st.write(
    "Enter the name of a Bollywood movie and get similar recommendations."
)

movie_name = st.text_input(
    "🎥 Enter Movie Name"
)

if st.button("Recommend"):

    if movie_name.strip() == "":

        st.warning("Please enter a movie name.")

    else:

        result = recommend(movie_name)

        if result == "Movie not found!":

            st.error("❌ Movie not found in our database.")

            st.info("Please check the spelling and try again.")

        else:

            st.success("Recommended Movies")

            for movie in result:

                with st.container():

                    col1, col2 = st.columns([1, 3])

                    with col2:
                      st.markdown(f"## 🎬 {movie['title']}")
                      st.write(f"**🎭 Actors:** {movie['actors']}")
                      st.write(f"**🎬 Director:** {movie['director']}")
                      st.write(f"**🎞 Genre:** {movie['genre']}")
                      st.write(f"**📅 Release Year:** {movie['year']}")
                      st.write(f"**⭐ Rating:** {movie['hitFlop']}/10")

                    st.divider()